# Generated by Django 5.1 on 2025-03-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(default="", max_length=100),
        ),
    ]
