# Generated by Django 5.1 on 2025-03-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("date", models.CharField(max_length=255)),
                ("isbn", models.CharField(max_length=13, unique=True)),
                ("available_copies", models.IntegerField(default=1)),
            ],
        ),
    ]
